// Publications
export const GET_PUBLICATIONS = 'GET_PUBLICATIONS';
export const PUBLICATIONS_ERROR = 'PUBLICATIONS_ERROR';
export const GET_FILTERED_PUBLICATIONS = 'GET_FILTERED_PUBLICATIONS';

// Publication
export const GET_PUBLICATION_BY_ID = 'GET_PUBLICATION_BY_ID';
export const PUBLICATION_ERROR = 'PUBLICATION_ERROR';

export const ADD_NEW_PUBLICATION = 'ADD_NEW_PUBLICATION';
